SPAWN_RATE = 0.15
WIDTH = 1080
HEIGHT = 720
CELL_SIZE = 5
ROWS = HEIGHT // CELL_SIZE
COLS = WIDTH // CELL_SIZE
FPS = 240
FLIP = 0
GRID = False
SCALE_FACTOR = 0.1  # Used to scale up and down the cell size
BACKGROUND_TOP = (24, 18, 37)  # Dark color for top of the screen
BACKGROUND_BOTTOM = (33, 71, 97)  # Light color for bottom of the screen
CELL_COLORS = [(60, 173, 100), (52, 152, 219)]  # Colors for alive and dead cells
BORDER_COLOR = (0,0,0)
BORDER_WIDTH = 2
PULSATE = False
RANDOM_FLIP = False
ZOMBIE = False
ZOMBIE_SPAWN_RATE = 0.00001
INFECT_PROBABILITY = 0.20
MAX_ZOMBIES = 5
START_PATTERN = "hex"